version: '3.8'

services:
  traefik:
    image: traefik:v2.5
    command:
      - --api.insecure=true
      - --providers.docker.defaultRule=Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)
      - --providers.file.filename=/etc/traefik/conf/services.yaml
      - --providers.docker
    ports:
      - "8080:8080"
      - "80:80"
    volumes:
      - $PWD/services.yaml:/etc/traefik/conf/services.yaml
      - /var/run/docker.sock:/var/run/docker.sock
